# Generated by Django 2.2.5 on 2019-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('fb_link', models.CharField(max_length=100)),
                ('tw_link', models.CharField(max_length=100)),
                ('insta_link', models.CharField(max_length=100)),
                ('linked_link', models.CharField(max_length=100)),
            ],
        ),
    ]
