# Generated by Django 2.2.5 on 2019-09-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('freelance_status', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.HeroArea')),
            ],
        ),
    ]
