# Generated by Django 2.2.5 on 2019-09-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_auto_20190912_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='my_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.HeroArea'),
        ),
    ]
