# Generated by Django 2.2.5 on 2019-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_detail', models.TextField()),
                ('project_image', models.FileField(upload_to='')),
            ],
        ),
    ]
