# Generated by Django 2.2.5 on 2019-09-23 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0010_mywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='project_github_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mywork',
            name='project_site_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
