# Generated by Django 2.2.5 on 2019-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0012_technicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSumarry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_working', models.IntegerField()),
                ('project_done', models.IntegerField()),
                ('award_receved', models.IntegerField()),
                ('happy_client', models.IntegerField()),
            ],
        ),
    ]
