# Generated by Django 2.2.5 on 2019-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0013_worksumarry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50)),
                ('sector_name', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='institute_name',
            field=models.CharField(max_length=5),
        ),
    ]
