# Generated by Django 2.2.5 on 2019-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0014_auto_20190924_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='project_category',
            field=models.CharField(choices=[('WEB', 'web'), ('ANDROID', 'android')], default='WEB', max_length=20),
        ),
    ]
